/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerBillingSystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.print.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.*;

/**
 *
 * @author Shrikrishna Sutar
 */
public class Customer_Billing_System extends javax.swing.JFrame {
    String iTax,isubTotal,iTotal;
    double itemcost[] =new double[20];
    /**
     * Creates new form Customer_Billing_System
     */
    public Customer_Billing_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtCustomerRef = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxyFirstname = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        jtxtPh = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jroom = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jmeal = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jTotalButton = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jprint = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        j1 = new javax.swing.JCheckBox();
        j2 = new javax.swing.JCheckBox();
        j4 = new javax.swing.JCheckBox();
        j3 = new javax.swing.JCheckBox();
        j8 = new javax.swing.JCheckBox();
        j7 = new javax.swing.JCheckBox();
        j6 = new javax.swing.JCheckBox();
        j5 = new javax.swing.JCheckBox();
        jtxtKerry = new javax.swing.JTextField();
        jtxtKim = new javax.swing.JTextField();
        jtxtSwindon = new javax.swing.JTextField();
        jtxtCoffee = new javax.swing.JTextField();
        jtxtLagos = new javax.swing.JTextField();
        jtxtKilburn = new javax.swing.JTextField();
        jtxtBlack = new javax.swing.JTextField();
        jtxtYork = new javax.swing.JTextField();
        j9 = new javax.swing.JCheckBox();
        j10 = new javax.swing.JCheckBox();
        jtxtCarlton = new javax.swing.JTextField();
        jtxtQueen = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        subtol = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        paid = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(176, 224, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));

        jPanel3.setBackground(new java.awt.Color(176, 224, 230));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Customer Ref:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 38, -1, 30));

        jtxtCustomerRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCustomerRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustomerRefActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtCustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 138, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FirstName:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mobile No :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Address 1:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Surname:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Post Code:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 142, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Check In Date:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Gender:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Date of Birth:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Room Type:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jtxyFirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxyFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxyFirstnameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxyFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 138, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 138, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAddressActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 138, -1));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostCodeActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 138, -1));

        jtxtPh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtPh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPhActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtPh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 138, -1));

        jtxtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtemailActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 138, -1));
        jPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 142, 20));
        jPanel3.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 142, 20));

        jroom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room Type", "1", "2", "3", "4" }));
        jroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jroomActionPerformed(evt);
            }
        });
        jPanel3.add(jroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 140, 30));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 140, 20));

        jmeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmealActionPerformed(evt);
            }
        });
        jPanel3.add(jmeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 140, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Meal :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Check Out Date:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Email:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jPanel16.setBackground(new java.awt.Color(176, 224, 230));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTotalButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotalButton.setText("Total");
        jTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalButtonActionPerformed(evt);
            }
        });
        jPanel16.add(jTotalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 40));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton15.setText("Reset");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 90, 40));

        jPanel17.setBackground(new java.awt.Color(176, 224, 230));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setText("Exit");
        jPanel17.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 40));

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setText("Print");
        jPanel17.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setText("Reset");
        jPanel17.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 40));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 330, 130));

        jPanel18.setBackground(new java.awt.Color(176, 224, 230));
        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton19.setText("Exit");
        jPanel18.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 40));

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton20.setText("Print");
        jPanel18.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton21.setText("Reset");
        jPanel18.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 40));

        jPanel19.setBackground(new java.awt.Color(176, 224, 230));
        jPanel19.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton22.setText("Exit");
        jPanel19.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 40));

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton23.setText("Print");
        jPanel19.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton24.setText("Reset");
        jPanel19.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 40));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 330, 130));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 330, 130));

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 330, 100));

        jPanel1.setBackground(new java.awt.Color(176, 224, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(176, 224, 230));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 500, 500));

        jPanel6.setBackground(new java.awt.Color(176, 224, 230));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(176, 224, 230));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 500, 500));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 78, 70, 660));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 560));

        jPanel12.setBackground(new java.awt.Color(176, 224, 230));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 90, 40));

        jprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jprint.setText("Print");
        jprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprintActionPerformed(evt);
            }
        });
        jPanel12.add(jprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, 40));

        jPanel13.setBackground(new java.awt.Color(176, 224, 230));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jPanel13.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Print");
        jPanel13.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Reset");
        jPanel13.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 40));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 330, 130));

        jPanel14.setBackground(new java.awt.Color(176, 224, 230));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Exit");
        jPanel14.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Print");
        jPanel14.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("Reset");
        jPanel14.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 40));

        jPanel15.setBackground(new java.awt.Color(176, 224, 230));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("Exit");
        jPanel15.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 40));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("Print");
        jPanel15.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("Reset");
        jPanel15.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 40));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 330, 130));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 330, 130));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 340, 120));

        jPanel4.setBackground(new java.awt.Color(176, 224, 230));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(176, 224, 230));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 150, 160)));

        j1.setBackground(new java.awt.Color(176, 224, 230));
        j1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j1.setText("Paneer Dry -₹195");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setBackground(new java.awt.Color(176, 224, 230));
        j2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j2.setText("Manchurian Dry -₹153");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j4.setBackground(new java.awt.Color(176, 224, 230));
        j4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j4.setText("Dal Makhani -₹192");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j3.setBackground(new java.awt.Color(176, 224, 230));
        j3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j3.setText("Butter Dosa -₹135");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        j8.setBackground(new java.awt.Color(176, 224, 230));
        j8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j8.setText("Chicken Biryani -₹200");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j7.setBackground(new java.awt.Color(176, 224, 230));
        j7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j7.setText("Mutton Kebab -₹250");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        j6.setBackground(new java.awt.Color(176, 224, 230));
        j6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j6.setText("Chicken Kebab -₹200");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j5.setBackground(new java.awt.Color(176, 224, 230));
        j5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j5.setText("Veg. Burger -₹72");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        jtxtKerry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtKerry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKerry.setText("0");
        jtxtKerry.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtKim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtKim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKim.setText("0");
        jtxtKim.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtSwindon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSwindon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSwindon.setText("0");
        jtxtSwindon.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtLagos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLagos.setText("0");
        jtxtLagos.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtKilburn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtKilburn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKilburn.setText("0");
        jtxtKilburn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtBlack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBlack.setText("0");
        jtxtBlack.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jtxtBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBlackActionPerformed(evt);
            }
        });

        jtxtYork.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtYork.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtYork.setText("0");
        jtxtYork.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        j9.setBackground(new java.awt.Color(176, 224, 230));
        j9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j9.setText("Mutton Biryani -₹250");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        j10.setBackground(new java.awt.Color(176, 224, 230));
        j10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j10.setText("Non-Veg Cutlet -₹150");
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });

        jtxtCarlton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCarlton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCarlton.setText("0");
        jtxtCarlton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtQueen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtQueen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtQueen.setText("0");
        jtxtQueen.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel20.setBackground(new java.awt.Color(95, 150, 160));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("* Non-Veg Dishes *");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        jLabel20.setVerifyInputWhenFocusTarget(false);

        jLabel22.setBackground(new java.awt.Color(95, 150, 160));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("* Veg Dishes *");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 102, 0)));
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtQueen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j2)
                                .addGap(5, 5, 5)
                                .addComponent(jtxtKerry, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtxtSwindon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jtxtYork, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel22)
                                        .addGap(22, 22, 22))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(11, 11, 11)))
                                .addComponent(jtxtKim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel20)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKerry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSwindon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtYork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtQueen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 380, 520));

        jPanel8.setBackground(new java.awt.Color(176, 224, 230));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(95, 158, 160)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 500, 500));

        jtxtTotal.setBackground(new java.awt.Color(176, 224, 230));
        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotal.setText("0");
        jtxtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 80, 30));

        jtxtTax.setBackground(new java.awt.Color(176, 224, 230));
        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTax.setText("0");
        jtxtTax.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 80, 30));

        jtxtSubTotal.setBackground(new java.awt.Color(176, 224, 230));
        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSubTotal.setText("0");
        jtxtSubTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 80, 30));

        subtol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subtol.setText("Sub Total");
        jPanel4.add(subtol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Total Cost");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 692, -1, 30));

        paid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paid.setText("Tax Paid");
        jPanel4.add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, 31));

        jLabel21.setBackground(new java.awt.Color(95, 150, 160));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Tax And Total Sum");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel21.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 187, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1320, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCustomerRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustomerRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustomerRefActionPerformed

    private void jtxyFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxyFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxyFirstnameActionPerformed

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurnameActionPerformed

    private void jtxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAddressActionPerformed

    private void jtxtPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPostCodeActionPerformed

    private void jtxtPhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPhActionPerformed

    private void jtxtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtemailActionPerformed

    private void jroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jroomActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void jmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmealActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
        if(j1.isSelected()){
            jtxtKim.setEnabled(true);
            jtxtKim.setText("");
            jtxtKim.requestFocus();
        }
        else{
            jtxtKim.setEnabled(false);
            jtxtKim.setText("0");
        }
    }//GEN-LAST:event_j1ActionPerformed
    private JFrame frame;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        frame=new JFrame("Exit"); 
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Customer Billing System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
    }




// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jtxtKim.setEnabled(false);
        jtxtKerry.setEnabled(false);
        jtxtCoffee.setEnabled(false);
        jtxtSwindon.setEnabled(false);
        jtxtYork.setEnabled(false);
        jtxtBlack.setEnabled(false);
        jtxtLagos.setEnabled(false);
        jtxtKilburn.setEnabled(false);
        jtxtCarlton.setEnabled(false);
        jtxtQueen.setEnabled(false);
        
        jtxtCustomerRef.setEnabled(false);
        int refs=5015+(int) (Math.random()*17238);
        String cRef="";
        cRef+=refs+1560;
        
        jtxtCustomerRef.setText(cRef);
        jtxyFirstname.setText(null);
        jtxtSurname.setText(null);
        jtxtAddress.setText(null);
        jtxtPostCode.setText(null);
        jtxtPh.setText(null);
        jtxtemail.setText(null);
        jtxtTax.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
         jDateChooser1.setDate(null);
         jDateChooser2.setDate(null);
         jDateChooser1.setDate(null);
         jmeal.setSelectedIndex(0);
         jroom.setSelectedIndex(0);
    }//GEN-LAST:event_formWindowActivated

    private void jtxtBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBlackActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         jtxtKim.setEnabled(false);
        jtxtKerry.setEnabled(false);
        jtxtCoffee.setEnabled(false);
        jtxtSwindon.setEnabled(false);
        jtxtYork.setEnabled(false);
        jtxtBlack.setEnabled(false);
        jtxtLagos.setEnabled(false);
        jtxtKilburn.setEnabled(false);
        jtxtCarlton.setEnabled(false);
        jtxtQueen.setEnabled(false);
        
        jtxtKim.setText("0");
        jtxtKerry.setText("0");
        jtxtCoffee.setText("0");
        jtxtSwindon.setText("0");
        jtxtYork.setText("0");
        jtxtBlack.setText("0");
        jtxtLagos.setText("0");
        jtxtKilburn.setText("0");
        jtxtCarlton.setText("0");
        jtxtQueen.setText("0");
        
        j1.setSelected(false);
        j2.setSelected(false);
        j3.setSelected(false);
        j4.setSelected(false);
        j5.setSelected(false);
        j6.setSelected(false);
        j7.setSelected(false);
        j8.setSelected(false);
        j9.setSelected(false);
        j10.setSelected(false);
        
        jtxtCustomerRef.setText(null);
        jtxtCustomerRef.setEnabled(false);
        int refs=5015+(int) (Math.random()*17238);
        String cRef="";
        cRef+=refs+1560;
        
        jtxtCustomerRef.setText(cRef);
        jtxyFirstname.setText(null);
        jtxtSurname.setText(null);
        jtxtAddress.setText(null);
        jtxtPostCode.setText(null);
        jtxtPh.setText(null);
        jtxtemail.setText(null);
        jtxtTax.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
         jDateChooser1.setDate(null);
         jDateChooser2.setDate(null);
         jDateChooser3.setDate(null);
         gender.setSelectedIndex(0);
         jmeal.setSelectedIndex(0);
         jroom.setSelectedIndex(0);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprintActionPerformed
        // TODO add your handling code here:
        
        try
        {
            jtxtReceipt.print();
        }
        catch(java.awt.print.PrinterException e){
         System.err.format("No Printer Found",e.getMessage());
        }
    }//GEN-LAST:event_jprintActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        if(j2.isSelected()){
            jtxtKerry.setEnabled(true);
            jtxtKerry.setText("");
            jtxtKerry.requestFocus();
        }
        else{
            jtxtKerry.setEnabled(false);
            jtxtKerry.setText("0");
        }
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
         if(j3.isSelected()){
            jtxtCoffee.setEnabled(true);
            jtxtCoffee.setText("");
            jtxtCoffee.requestFocus();
        }
        else{
            jtxtCoffee.setEnabled(false);
            jtxtCoffee.setText("0");
        }
    }//GEN-LAST:event_j3ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
         if(j4.isSelected()){
            jtxtSwindon.setEnabled(true);
            jtxtSwindon.setText("");
            jtxtSwindon.requestFocus();
        }
        else{
            jtxtSwindon.setEnabled(false);
            jtxtSwindon.setText("0");
        }
    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
        if(j5.isSelected()){
            jtxtYork.setEnabled(true);
            jtxtYork.setText("");
            jtxtYork.requestFocus();
        }
        else{
            jtxtYork.setEnabled(false);
            jtxtYork.setText("0");
        }
    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
         if(j6.isSelected()){
            jtxtBlack.setEnabled(true);
            jtxtBlack.setText("");
            jtxtBlack.requestFocus();
        }
        else{
            jtxtBlack.setEnabled(false);
            jtxtBlack.setText("0");
        }
    }//GEN-LAST:event_j6ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
         if(j7.isSelected()){
            jtxtLagos.setEnabled(true);
            jtxtLagos.setText("");
            jtxtLagos.requestFocus();
        }
        else{
            jtxtLagos.setEnabled(false);
            jtxtLagos.setText("0");
        }
    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
        if(j8.isSelected()){
            jtxtKilburn.setEnabled(true);
            jtxtKilburn.setText("");
            jtxtKilburn.requestFocus();
        }
        else{
            jtxtKilburn.setEnabled(false);
            jtxtKilburn.setText("0");
        }
    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
         if(j9.isSelected()){
            jtxtCarlton.setEnabled(true);
            jtxtCarlton.setText("");
            jtxtCarlton.requestFocus();
        }
        else{
            jtxtCarlton.setEnabled(false);
            jtxtCarlton.setText("0");
        }
    }//GEN-LAST:event_j9ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
          if(j10.isSelected()){
            jtxtQueen.setEnabled(true);
            jtxtQueen.setText("");
            jtxtQueen.requestFocus();
        }
        else{
            jtxtQueen.setEnabled(false);
            jtxtQueen.setText("0");
        }
    }//GEN-LAST:event_j10ActionPerformed

    private void jTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalButtonActionPerformed
        // TODO add your handling code here:
        itemcost[0]=Double.parseDouble(jtxtKim.getText())*195;
        itemcost[1]=Double.parseDouble(jtxtKerry.getText())*153;
        itemcost[2]=Double.parseDouble(jtxtCoffee.getText())*135;
        itemcost[3]=Double.parseDouble(jtxtSwindon.getText())*192;
        itemcost[4]=Double.parseDouble(jtxtYork.getText())*72;
        itemcost[5]=Double.parseDouble(jtxtBlack.getText())*200;
        itemcost[6]=Double.parseDouble(jtxtLagos.getText())*250;
        itemcost[7]=Double.parseDouble(jtxtKilburn.getText())*200;
        itemcost[8]=Double.parseDouble(jtxtCarlton.getText())*250;
        itemcost[9]=Double.parseDouble(jtxtQueen.getText())*150;
        
        itemcost[10]=itemcost[0]+itemcost[1]+itemcost[2]+itemcost[3]+itemcost[4];
        itemcost[11]=itemcost[5]+itemcost[6]+itemcost[7]+itemcost[8]+itemcost[9];
        
        itemcost[12]=itemcost[10]+itemcost[11];
        
        iTax=String.format("₹ .2f" ,itemcost[12]/100);
        isubTotal=String.format("₹ %.2f" ,itemcost[12]);
        iTotal=String.format("₹ %.2f" ,itemcost[12]+(itemcost[12]/100));
        
        jtxtTax.setText(iTax);
        jtxtSubTotal.setText(isubTotal);
        jtxtTotal.setText(iTotal);
        
        //======================================================================
        
        jtxtReceipt.setEnabled(true);
        
        int refs=1325+(int) (Math.random()*4238);
        
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate=new SimpleDateFormat("dd-MM-yyyy");
        tDate.format(timer.getTime());
        
        jtxtReceipt.append("\t Customer Billing System \n"+
                
        "\n==========================================\t"+
        "\nReference:\t\t\t"+refs+
        "\n==========================================\t"+
                
               
                "\nCustomer Ref:\t\t\t"+jtxtCustomerRef.getText()+
                "\nFirst Name:\t\t\t"+jtxyFirstname.getText()+
                "\nSur Name:\t\t\t"+jtxtSurname.getText()+
         "\n==========================================\t\n"+
                "\nPaneer Dry:\t\t\t"+jtxtKim.getText()+
                "\nManchurian Dry:\t\t"+jtxtKerry.getText()+
                "\nButter Dosa:\t\t\t"+jtxtCoffee.getText()+
                "\nDal Makhani:\t\t\t"+jtxtSwindon.getText()+
                "\nVeg. Burger:\t\t\t"+jtxtYork.getText()+
                "\nChicken Kebab:\t\t\t"+jtxtBlack.getText()+
                "\nMutton Kebab:\t\t\t"+jtxtLagos.getText()+
                "\nChicken Biryani:\t\t"+jtxtKilburn.getText()+
                "\nMutton Biryani:\t\t\t"+jtxtCarlton.getText()+
                "\nNon-Veg Cutlet:\t\t\t"+jtxtQueen.getText()+
         "\n\n\n==========================================\t"+
                "\nTax:\t\t\t"+iTax+
                "\nSub Total:\t\t\t"+isubTotal+
                "\nTotal:\t\t\t"+iTotal+
         "\n==========================================\t"+
                
                                     "\n"+
          "\n\n\tThanks For Visiting At Our Shop\n"+
         "\n==========================================\t"+
         "\nDate: "+tDate.format(timer.getTime())+
         "\tTime: "+tTime.format(timer.getTime()));
                
                
        
        
    }//GEN-LAST:event_jTotalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Billing_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Billing_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Billing_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Billing_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Billing_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JCheckBox j1;
    private javax.swing.JCheckBox j10;
    private javax.swing.JCheckBox j2;
    private javax.swing.JCheckBox j3;
    private javax.swing.JCheckBox j4;
    private javax.swing.JCheckBox j5;
    private javax.swing.JCheckBox j6;
    private javax.swing.JCheckBox j7;
    private javax.swing.JCheckBox j8;
    private javax.swing.JCheckBox j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTotalButton;
    private javax.swing.JComboBox<String> jmeal;
    private javax.swing.JButton jprint;
    private javax.swing.JComboBox<String> jroom;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtBlack;
    private javax.swing.JTextField jtxtCarlton;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JTextField jtxtCustomerRef;
    private javax.swing.JTextField jtxtKerry;
    private javax.swing.JTextField jtxtKilburn;
    private javax.swing.JTextField jtxtKim;
    private javax.swing.JTextField jtxtLagos;
    private javax.swing.JTextField jtxtPh;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextField jtxtQueen;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtSwindon;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtYork;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxyFirstname;
    private javax.swing.JLabel paid;
    private javax.swing.JLabel subtol;
    // End of variables declaration//GEN-END:variables
}
